// This file is auto-generated by @hey-api/openapi-ts

export type RegisterDto = {
  email: string
  password: string
  firstName: string
  lastName: string
  phoneNumber: string
}

export type UserResponse = {
  email: string
  firstName: string
  lastName: string
  phoneNumber: string
}

export type LoginDto = {
  email: string
  password: string
}

export type UserRequestDto = {
  email: string
  firstName: string
  lastName: string
  phoneNumber: string
  password: string
}

export type AuthControllerRegisterData = {
  body: RegisterDto
  path?: never
  query?: never
  url: '/auth/register'
}

export type AuthControllerRegisterResponses = {
  200: UserResponse
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses]

export type AuthControllerLoginData = {
  body: LoginDto
  path?: never
  query?: never
  url: '/auth/login'
}

export type AuthControllerLoginResponses = {
  200: UserResponse
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type UsersControllerFindAllData = {
  body?: never
  path?: never
  query?: never
  url: '/users'
}

export type UsersControllerFindAllResponses = {
  200: unknown
}

export type UsersControllerCreateData = {
  body: UserRequestDto
  path?: never
  query?: never
  url: '/users'
}

export type UsersControllerCreateResponses = {
  201: unknown
}

export type UsersControllerRemoveData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/users/{id}'
}

export type UsersControllerRemoveResponses = {
  200: unknown
}

export type UsersControllerFindOneData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/users/{id}'
}

export type UsersControllerFindOneResponses = {
  200: unknown
}

export type UsersControllerUpdateData = {
  body: UserRequestDto
  path: {
    id: number
  }
  query?: never
  url: '/users/{id}'
}

export type UsersControllerUpdateResponses = {
  200: unknown
}

export type ClientOptions = {
  baseUrl: 'http://localhost:3000' | (string & {})
}
