// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

export const zRegisterDto = z.object({
  email: z.email(),
  password: z.string(),
  firstName: z.string().min(2),
  lastName: z.string().min(2),
  phoneNumber: z.string(),
})

export const zUserResponse = z.object({
  email: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  phoneNumber: z.string(),
})

export const zLoginDto = z.object({
  email: z.email(),
  password: z.string(),
})

export const zUserRequestDto = z.object({
  email: z.string().regex(/^[\w-.]+@([\w-]+\.)+[\w-]{2,4}$/),
  firstName: z.string(),
  lastName: z.string(),
  phoneNumber: z.string(),
  password: z.string(),
})

export const zAuthControllerRegisterData = z.object({
  body: zRegisterDto,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zAuthControllerRegisterResponse = zUserResponse

export const zAuthControllerLoginData = z.object({
  body: zLoginDto,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zAuthControllerLoginResponse = zUserResponse

export const zUsersControllerFindAllData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zUsersControllerCreateData = z.object({
  body: zUserRequestDto,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zUsersControllerRemoveData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.number(),
  }),
  query: z.optional(z.never()),
})

export const zUsersControllerFindOneData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.number(),
  }),
  query: z.optional(z.never()),
})

export const zUsersControllerUpdateData = z.object({
  body: zUserRequestDto,
  path: z.object({
    id: z.number(),
  }),
  query: z.optional(z.never()),
})
